package com.example.backend.dto;

import java.util.Date;

public class BookDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_name
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.image_url
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.exam_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_name
     *
     * @return the value of books.book_name
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_name
     *
     * @param bookName the value for books.book_name
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.image_url
     *
     * @return the value of books.image_url
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.image_url
     *
     * @param imageUrl the value for books.image_url
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.exam_id
     *
     * @return the value of books.exam_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.exam_id
     *
     * @param examId the value for books.exam_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.created_at
     *
     * @return the value of books.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.created_at
     *
     * @param createdAt the value for books.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.updated_at
     *
     * @return the value of books.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.updated_at
     *
     * @param updatedAt the value for books.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}