package com.example.backend.dto;

import java.util.Date;

public class ChapterDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.book_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.chapter_title
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private String chapterTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.order_no
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapters.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.id
     *
     * @return the value of chapters.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.id
     *
     * @param id the value for chapters.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.book_id
     *
     * @return the value of chapters.book_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.book_id
     *
     * @param bookId the value for chapters.book_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.chapter_title
     *
     * @return the value of chapters.chapter_title
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public String getChapterTitle() {
        return chapterTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.chapter_title
     *
     * @param chapterTitle the value for chapters.chapter_title
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setChapterTitle(String chapterTitle) {
        this.chapterTitle = chapterTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.order_no
     *
     * @return the value of chapters.order_no
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.order_no
     *
     * @param orderNo the value for chapters.order_no
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.created_at
     *
     * @return the value of chapters.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.created_at
     *
     * @param createdAt the value for chapters.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapters.updated_at
     *
     * @return the value of chapters.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapters.updated_at
     *
     * @param updatedAt the value for chapters.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}