package com.example.backend.dto;

import java.util.Date;

public class ChapterStatusDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.progress_percent
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer progressPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.last_studied
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date lastStudied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_status.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.id
     *
     * @return the value of chapter_status.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.id
     *
     * @param id the value for chapter_status.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.user_id
     *
     * @return the value of chapter_status.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.user_id
     *
     * @param userId the value for chapter_status.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.chapter_id
     *
     * @return the value of chapter_status.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.chapter_id
     *
     * @param chapterId the value for chapter_status.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.progress_percent
     *
     * @return the value of chapter_status.progress_percent
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getProgressPercent() {
        return progressPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.progress_percent
     *
     * @param progressPercent the value for chapter_status.progress_percent
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setProgressPercent(Integer progressPercent) {
        this.progressPercent = progressPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.last_studied
     *
     * @return the value of chapter_status.last_studied
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getLastStudied() {
        return lastStudied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.last_studied
     *
     * @param lastStudied the value for chapter_status.last_studied
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setLastStudied(Date lastStudied) {
        this.lastStudied = lastStudied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.created_at
     *
     * @return the value of chapter_status.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.created_at
     *
     * @param createdAt the value for chapter_status.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_status.updated_at
     *
     * @return the value of chapter_status.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_status.updated_at
     *
     * @param updatedAt the value for chapter_status.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}