package com.example.backend.dto;

import java.util.Date;

public class ExamDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.user_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.exam_name
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.exam_date
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Date examDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.estimated_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer estimatedStudyHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exams.estimated_daily_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    private Integer estimatedDailyStudyHours;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.id
     *
     * @return the value of exams.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.id
     *
     * @param id the value for exams.id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.user_id
     *
     * @return the value of exams.user_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.user_id
     *
     * @param userId the value for exams.user_id
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.exam_name
     *
     * @return the value of exams.exam_name
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.exam_name
     *
     * @param examName the value for exams.exam_name
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setExamName(String examName) {
        this.examName = examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.exam_date
     *
     * @return the value of exams.exam_date
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.exam_date
     *
     * @param examDate the value for exams.exam_date
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.status
     *
     * @return the value of exams.status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.status
     *
     * @param status the value for exams.status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.created_at
     *
     * @return the value of exams.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.created_at
     *
     * @param createdAt the value for exams.created_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.updated_at
     *
     * @return the value of exams.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.updated_at
     *
     * @param updatedAt the value for exams.updated_at
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.estimated_study_hours
     *
     * @return the value of exams.estimated_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getEstimatedStudyHours() {
        return estimatedStudyHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.estimated_study_hours
     *
     * @param estimatedStudyHours the value for exams.estimated_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setEstimatedStudyHours(Integer estimatedStudyHours) {
        this.estimatedStudyHours = estimatedStudyHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exams.estimated_daily_study_hours
     *
     * @return the value of exams.estimated_daily_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public Integer getEstimatedDailyStudyHours() {
        return estimatedDailyStudyHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exams.estimated_daily_study_hours
     *
     * @param estimatedDailyStudyHours the value for exams.estimated_daily_study_hours
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    public void setEstimatedDailyStudyHours(Integer estimatedDailyStudyHours) {
        this.estimatedDailyStudyHours = estimatedDailyStudyHours;
    }
}