package com.example.backend.dto;

import java.util.Date;

public class StudyLogDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.study_date
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date studyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.duration_minutes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Integer durationMinutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.notes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_logs.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.id
     *
     * @return the value of study_logs.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.id
     *
     * @param id the value for study_logs.id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.user_id
     *
     * @return the value of study_logs.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.user_id
     *
     * @param userId the value for study_logs.user_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.chapter_id
     *
     * @return the value of study_logs.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.chapter_id
     *
     * @param chapterId the value for study_logs.chapter_id
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.study_date
     *
     * @return the value of study_logs.study_date
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getStudyDate() {
        return studyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.study_date
     *
     * @param studyDate the value for study_logs.study_date
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setStudyDate(Date studyDate) {
        this.studyDate = studyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.duration_minutes
     *
     * @return the value of study_logs.duration_minutes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Integer getDurationMinutes() {
        return durationMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.duration_minutes
     *
     * @param durationMinutes the value for study_logs.duration_minutes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setDurationMinutes(Integer durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.notes
     *
     * @return the value of study_logs.notes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.notes
     *
     * @param notes the value for study_logs.notes
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.created_at
     *
     * @return the value of study_logs.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.created_at
     *
     * @param createdAt the value for study_logs.created_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_logs.updated_at
     *
     * @return the value of study_logs.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_logs.updated_at
     *
     * @param updatedAt the value for study_logs.updated_at
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}