package com.example.backend.mapper;

import com.example.backend.dto.BookDto;
import com.example.backend.dto.BookDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    long countByExample(BookDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByExample(BookDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insert(BookDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insertSelective(BookDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    List<BookDto> selectByExample(BookDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    BookDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExampleSelective(@Param("row") BookDto row, @Param("example") BookDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExample(@Param("row") BookDto row, @Param("example") BookDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKeySelective(BookDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKey(BookDto row);
}