package com.example.backend.mapper;

import com.example.backend.entity.Book;
import com.example.backend.entity.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insert(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insertSelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExample(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKeySelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKey(Book row);
}