package com.example.backend.mapper;

import com.example.backend.entity.ChapterStatus;
import com.example.backend.entity.ChapterStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChapterStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    long countByExample(ChapterStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int deleteByExample(ChapterStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int insert(ChapterStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int insertSelective(ChapterStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    List<ChapterStatus> selectByExample(ChapterStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    ChapterStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int updateByExampleSelective(@Param("row") ChapterStatus row, @Param("example") ChapterStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int updateByExample(@Param("row") ChapterStatus row, @Param("example") ChapterStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int updateByPrimaryKeySelective(ChapterStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Fri Nov 28 16:54:25 JST 2025
     */
    int updateByPrimaryKey(ChapterStatus row);
}