package com.example.backend.mapper;

import com.example.backend.entity.Chapter;
import com.example.backend.entity.ChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    long countByExample(ChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByExample(ChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insert(Chapter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insertSelective(Chapter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    List<Chapter> selectByExample(ChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    Chapter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") Chapter row, @Param("example") ChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExample(@Param("row") Chapter row, @Param("example") ChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKeySelective(Chapter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKey(Chapter row);
}