package com.example.backend.mapper;

import com.example.backend.dto.ChapterStatusDto;
import com.example.backend.dto.ChapterStatusDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChapterStatusDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    long countByExample(ChapterStatusDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByExample(ChapterStatusDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insert(ChapterStatusDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insertSelective(ChapterStatusDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    List<ChapterStatusDto> selectByExample(ChapterStatusDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    ChapterStatusDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExampleSelective(@Param("row") ChapterStatusDto row, @Param("example") ChapterStatusDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExample(@Param("row") ChapterStatusDto row, @Param("example") ChapterStatusDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKeySelective(ChapterStatusDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_status
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKey(ChapterStatusDto row);
}