package com.example.backend.mapper;

import com.example.backend.dto.ChapterDto;
import com.example.backend.dto.ChapterDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChapterDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    long countByExample(ChapterDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int deleteByExample(ChapterDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int insert(ChapterDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int insertSelective(ChapterDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    List<ChapterDto> selectByExample(ChapterDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    ChapterDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByExampleSelective(@Param("row") ChapterDto row, @Param("example") ChapterDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByExample(@Param("row") ChapterDto row, @Param("example") ChapterDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByPrimaryKeySelective(ChapterDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapters
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByPrimaryKey(ChapterDto row);
}