package com.example.backend.mapper;

import com.example.backend.entity.Exam;
import com.example.backend.entity.ExamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    long countByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insert(Exam row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insertSelective(Exam row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    List<Exam> selectByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    Exam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") Exam row, @Param("example") ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExample(@Param("row") Exam row, @Param("example") ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKeySelective(Exam row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKey(Exam row);
}