package com.example.backend.mapper;

import com.example.backend.dto.ExamDto;
import com.example.backend.dto.ExamDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    long countByExample(ExamDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByExample(ExamDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insert(ExamDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insertSelective(ExamDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    List<ExamDto> selectByExample(ExamDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    ExamDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExampleSelective(@Param("row") ExamDto row, @Param("example") ExamDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExample(@Param("row") ExamDto row, @Param("example") ExamDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKeySelective(ExamDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exams
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKey(ExamDto row);
}