package com.example.backend.mapper;

import com.example.backend.entity.StudyLog;
import com.example.backend.entity.StudyLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    long countByExample(StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByExample(StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insert(StudyLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int insertSelective(StudyLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    List<StudyLog> selectByExampleWithBLOBs(StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    List<StudyLog> selectByExample(StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    StudyLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") StudyLog row, @Param("example") StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") StudyLog row, @Param("example") StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByExample(@Param("row") StudyLog row, @Param("example") StudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKeySelective(StudyLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKeyWithBLOBs(StudyLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    int updateByPrimaryKey(StudyLog row);
}