package com.example.backend.mapper;

import com.example.backend.dto.StudyLogDto;
import com.example.backend.dto.StudyLogDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyLogDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    long countByExample(StudyLogDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByExample(StudyLogDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insert(StudyLogDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int insertSelective(StudyLogDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    List<StudyLogDto> selectByExample(StudyLogDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    StudyLogDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExampleSelective(@Param("row") StudyLogDto row, @Param("example") StudyLogDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByExample(@Param("row") StudyLogDto row, @Param("example") StudyLogDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKeySelective(StudyLogDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_logs
     *
     * @mbg.generated Wed Dec 24 00:07:19 JST 2025
     */
    int updateByPrimaryKey(StudyLogDto row);
}