package com.example.backend.mapper;

import com.example.backend.dto.UserDto;
import com.example.backend.dto.UserDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    long countByExample(UserDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int deleteByExample(UserDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int insert(UserDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int insertSelective(UserDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    List<UserDto> selectByExample(UserDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    UserDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByExampleSelective(@Param("row") UserDto row, @Param("example") UserDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByExample(@Param("row") UserDto row, @Param("example") UserDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByPrimaryKeySelective(UserDto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 21 17:24:02 JST 2025
     */
    int updateByPrimaryKey(UserDto row);
}