package com.example.backend.entity;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_name
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.exam_id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    private Integer examId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_name
     *
     * @return the value of books.book_name
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_name
     *
     * @param bookName the value for books.book_name
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.exam_id
     *
     * @return the value of books.exam_id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.exam_id
     *
     * @param examId the value for books.exam_id
     *
     * @mbg.generated Mon Nov 24 11:41:43 JST 2025
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }
}